"""SSH execution layer built on paramiko.

Features
--------
* key and/or password authentication (per system key or the global key)
* host key pinning (keys sent during enrollment or trust-on-first-use)
* root execution via ``sudo`` (with or without password)
* streaming script execution with cancel support
* "detached" execution for long running jobs (e.g. release upgrades): the
  script keeps running on the remote host even if the SSH/WireGuard
  connection drops, and the output is tailed until it finishes.
"""
from __future__ import annotations

import base64
import codecs
import logging
import select
import shlex
import socket
import time
import uuid
from dataclasses import dataclass, field
from typing import Callable, Optional

import paramiko

from . import security, sshkeys
from .models import (AUTH_PASSWORD, SUDO_NONE, SUDO_NOPASSWD, SUDO_PASSWORD, System)

log = logging.getLogger(__name__)

OutputCB = Callable[[str], None]
CancelCB = Callable[[], bool]

HOSTKEY_ORDER = ["ssh-ed25519", "ecdsa-sha2-nistp256", "ecdsa-sha2-nistp384", "ecdsa-sha2-nistp521", "ssh-rsa"]
DETACHED_DIR = "/var/lib/servermanager-jobs"
DETACHED_DIED = -999

SCRIPT_PRELUDE = """#!/bin/bash
# generated by servermanager
set -o pipefail
export DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a APT_LISTCHANGES_FRONTEND=none
export LC_ALL=C.UTF-8 LANG=C.UTF-8 TERM=dumb
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
__sm_self="$0"
trap 'rm -f "$__sm_self" "${__sm_self%.sh}.pid"' EXIT
echo $$ > "${__sm_self%.sh}.pid" 2>/dev/null || true
"""


class SSHError(Exception):
    pass


class HostKeyError(SSHError):
    pass


class CancelledError(SSHError):
    pass


@dataclass
class Target:
    name: str
    host: str
    port: int = 22
    username: str = "root"
    password: str = ""
    pkey: Optional[paramiko.PKey] = None
    sudo_mode: str = SUDO_NONE
    sudo_password: str = ""
    host_keys: str = ""
    connect_timeout: int = 15
    system_id: Optional[int] = None
    extra: dict = field(default_factory=dict)

    @property
    def is_root(self) -> bool:
        return self.username == "root" or self.sudo_mode == SUDO_NONE


@dataclass
class Result:
    exit_code: int
    stdout: str
    stderr: str

    @property
    def ok(self) -> bool:
        return self.exit_code == 0


def target_from_system(system: System, connect_timeout: int = 15) -> Target:
    pkey = None
    if system.private_key_enc:
        pkey = sshkeys.load_private_key(security.decrypt(system.private_key_enc),
                                        security.decrypt(system.key_passphrase_enc) or None)
    elif system.auth_method != AUTH_PASSWORD:
        pkey = sshkeys.default_private_key()
    password = security.decrypt(system.password_enc) if system.password_enc else ""
    sudo_mode = system.sudo_mode if system.username != "root" else SUDO_NONE
    sudo_pw = security.decrypt(system.sudo_password_enc) if system.sudo_password_enc else ""
    if sudo_mode == SUDO_PASSWORD and not sudo_pw:
        sudo_pw = password
    return Target(name=system.name, host=system.host, port=system.port or 22, username=system.username or "root",
                  password=password, pkey=pkey, sudo_mode=sudo_mode, sudo_password=sudo_pw,
                  host_keys=system.host_keys or "", connect_timeout=connect_timeout, system_id=system.id)


def parse_host_keys(text: str) -> list[tuple[str, str]]:
    keys = []
    for line in (text or "").splitlines():
        parts = line.strip().split()
        if len(parts) >= 2 and parts[0] in HOSTKEY_ORDER:
            try:
                base64.b64decode(parts[1], validate=True)
            except ValueError:
                continue
            keys.append((parts[0], parts[1]))
    keys.sort(key=lambda k: HOSTKEY_ORDER.index(k[0]))
    return keys


def host_key_fingerprint(key_type: str, b64: str) -> str:
    import hashlib
    digest = hashlib.sha256(base64.b64decode(b64)).digest()
    return f"{key_type} SHA256:{base64.b64encode(digest).decode().rstrip('=')}"


class _PinPolicy(paramiko.MissingHostKeyPolicy):
    def __init__(self, have_keys: bool):
        self.have_keys = have_keys
        self.new_key: Optional[paramiko.PKey] = None

    def missing_host_key(self, client, hostname, key):
        if self.have_keys:
            raise HostKeyError(
                f"Unerwarteter Hostkey-Typ {key.get_name()} von {hostname}. Der gespeicherte Hostkey passt nicht - "
                "bitte prüfen und ggf. in den System-Einstellungen zurücksetzen.")
        self.new_key = key  # trust on first use


class Connection:
    def __init__(self, target: Target, on_new_host_key: Optional[Callable[[str], None]] = None):
        self.target = target
        self.on_new_host_key = on_new_host_key
        self.client: Optional[paramiko.SSHClient] = None

    # ------------------------------------------------------------------
    def connect(self) -> "Connection":
        t = self.target
        if not t.host:
            raise SSHError("Keine Zieladresse konfiguriert.")
        client = paramiko.SSHClient()
        known = parse_host_keys(t.host_keys)
        hk_name = t.host if t.port == 22 else f"[{t.host}]:{t.port}"
        for ktype, b64 in known:
            try:
                client.get_host_keys().add(hk_name, ktype,
                                           paramiko.PKey.from_type_string(ktype, base64.b64decode(b64)))
            except Exception as exc:  # noqa: BLE001
                log.warning("cannot load host key %s: %s", ktype, exc)
        policy = _PinPolicy(bool(known))
        client.set_missing_host_key_policy(policy)
        try:
            client.connect(t.host, port=t.port, username=t.username, password=t.password or None,
                           pkey=t.pkey, timeout=t.connect_timeout, banner_timeout=t.connect_timeout,
                           auth_timeout=t.connect_timeout, allow_agent=False, look_for_keys=False)
        except paramiko.BadHostKeyException as exc:
            client.close()
            raise HostKeyError(
                f"WARNUNG: Hostkey von {t.host} hat sich geändert (erwartet {exc.expected_key.get_name()}). "
                "Möglicher Man-in-the-Middle-Angriff oder neu installiertes System. Verbindung abgelehnt - "
                "Hostkey in den System-Einstellungen prüfen/zurücksetzen.") from exc
        except HostKeyError:
            client.close()
            raise
        except paramiko.AuthenticationException as exc:
            client.close()
            raise SSHError(f"Authentifizierung fehlgeschlagen für {t.username}@{t.host}: {exc}") from exc
        except (socket.timeout, TimeoutError) as exc:
            client.close()
            raise SSHError(f"Zeitüberschreitung beim Verbinden mit {t.host}:{t.port}") from exc
        except (OSError, paramiko.SSHException) as exc:
            client.close()
            raise SSHError(f"Verbindung zu {t.host}:{t.port} fehlgeschlagen: {exc}") from exc
        transport = client.get_transport()
        if transport:
            transport.set_keepalive(20)
        self.client = client
        if policy.new_key is not None and self.on_new_host_key:
            self.on_new_host_key(f"{policy.new_key.get_name()} {policy.new_key.get_base64()}")
        return self

    def close(self) -> None:
        if self.client:
            try:
                self.client.close()
            finally:
                self.client = None

    def __enter__(self) -> "Connection":
        if self.client is None:
            self.connect()
        return self

    def __exit__(self, *exc) -> None:
        self.close()

    @property
    def alive(self) -> bool:
        tr = self.client.get_transport() if self.client else None
        return bool(tr and tr.is_active())

    # ------------------------------------------------------------------
    def _root_wrap(self, cmd: str) -> tuple[str, Optional[str]]:
        """Return (command, stdin prefix) to run ``cmd`` as root."""
        t = self.target
        if t.is_root:
            return cmd, None
        inner = shlex.quote(cmd)
        if t.sudo_mode == SUDO_NOPASSWD:
            return f"sudo -n -H -- bash -c {inner}", None
        if t.sudo_mode == SUDO_PASSWORD:
            return f"sudo -k -S -p '' -H -- bash -c {inner}", t.sudo_password + "\n"
        return cmd, None

    def _open(self, cmd: str, combine: bool = True) -> paramiko.Channel:
        if not self.client:
            self.connect()
        transport = self.client.get_transport()  # type: ignore[union-attr]
        if transport is None or not transport.is_active():
            raise SSHError("SSH-Verbindung getrennt")
        chan = transport.open_session(timeout=30)
        if combine:
            chan.set_combine_stderr(True)
        chan.exec_command(cmd)
        return chan

    def _pump(self, chan: paramiko.Channel, on_out: Callable[[bytes], None],
              on_err: Optional[Callable[[bytes], None]] = None, tick: Optional[Callable[[], None]] = None,
              timeout: Optional[float] = None, what: str = "") -> None:
        """Read stdout/stderr until the remote side sent EOF and the exit status.

        Waiting for EOF (not only for the exit status) matters: OpenSSH may send
        the exit status before the last output bytes arrived.
        """
        err_cb = on_err or (lambda _d: None)
        deadline = time.monotonic() + timeout if timeout else None
        status_seen: Optional[float] = None
        while True:
            got = False
            if chan.recv_ready():
                data = chan.recv(1 << 20)
                if data:
                    on_out(data)
                    got = True
            if chan.recv_stderr_ready():
                data = chan.recv_stderr(65536)
                if data:
                    err_cb(data)
                    got = True
            if got:
                continue
            if chan.exit_status_ready():
                if status_seen is None:
                    status_seen = time.monotonic()
                # EOF received (or channel closed): everything sent before is buffered.
                # A background child keeping stdout open must not block us forever.
                if chan.eof_received or chan.closed or time.monotonic() - status_seen > 10:
                    while chan.recv_ready():
                        on_out(chan.recv(1 << 20))
                    while chan.recv_stderr_ready():
                        err_cb(chan.recv_stderr(65536))
                    return
            elif chan.closed:
                raise SSHError("SSH-Kanal unerwartet geschlossen")
            if tick:
                tick()
            if deadline and time.monotonic() > deadline:
                raise SSHError(f"Zeitüberschreitung{': ' + what if what else ''}")
            if not self.alive:
                raise SSHError("SSH-Verbindung verloren")
            select.select([chan], [], [], 0.3)

    def exec(self, cmd: str, root: bool = False, stdin: Optional[bytes] = None, timeout: int = 120) -> Result:
        """Run a short command and collect stdout/stderr."""
        prefix = None
        if root:
            cmd, prefix = self._root_wrap(cmd)
        chan = self._open(cmd, combine=False)
        try:
            if prefix:
                chan.sendall(prefix.encode())
            if stdin:
                chan.sendall(stdin)
            chan.shutdown_write()
            out, err = bytearray(), bytearray()
            self._pump(chan, out.extend, err.extend, timeout=timeout, what=cmd[:80])
            code = chan.recv_exit_status()
            return Result(code, out.decode("utf-8", "replace"), err.decode("utf-8", "replace"))
        finally:
            chan.close()

    def check(self, cmd: str, root: bool = False, timeout: int = 120) -> str:
        res = self.exec(cmd, root=root, timeout=timeout)
        if not res.ok:
            raise SSHError(f"Befehl fehlgeschlagen ({res.exit_code}): {(res.stderr or res.stdout).strip()[:500]}")
        return res.stdout

    # ------------------------------------------------------------------
    @staticmethod
    def build_script(body: str, env: Optional[dict] = None) -> str:
        lines = [SCRIPT_PRELUDE]
        for key, value in (env or {}).items():
            if not key.replace("_", "").isalnum():
                raise ValueError(f"invalid env name {key}")
            lines.append(f"export {key}={shlex.quote(str(value))}")
        lines.append(body)
        return "\n".join(lines) + "\n"

    def upload_script(self, script: str, path: Optional[str] = None) -> str:
        path = path or f"/tmp/.sm-{uuid.uuid4().hex}.sh"
        res = self.exec(f"umask 077 && cat > {shlex.quote(path)}", stdin=script.encode(), timeout=60)
        if not res.ok:
            raise SSHError(f"Skript konnte nicht übertragen werden: {res.stderr.strip()}")
        return path

    def run_script(self, body: str, env: Optional[dict] = None, root: bool = True,
                   on_output: Optional[OutputCB] = None, cancel: Optional[CancelCB] = None,
                   timeout: Optional[int] = None) -> int:
        """Execute a bash script and stream combined output. Returns the exit code.

        Raises CancelledError when ``cancel()`` requested an abort and SSHError on timeout.
        """
        path = self.upload_script(self.build_script(body, env))
        qpath = shlex.quote(path)
        prefix = None
        if root and not self.target.is_root:
            # The uploaded file belongs to the login user - read it into memory as root before
            # running it, so it cannot be modified while root executes it.
            inner = f's=$(cat {qpath}) && rm -f {qpath} && exec bash -c "$s" {qpath}'
            cmd, prefix = self._root_wrap(f"setsid -w bash -c {shlex.quote(inner)}")
        else:
            cmd = f"setsid -w bash {qpath}"
        chan = self._open(cmd, combine=True)
        decoder = codecs.getincrementaldecoder("utf-8")("replace")
        emit = on_output or (lambda s: None)
        state = {"cancelled": False, "timed_out": False}
        started = time.monotonic()

        def tick() -> None:
            if not state["cancelled"] and not state["timed_out"]:
                if cancel and cancel():
                    state["cancelled"] = True
                    emit("\n[servermanager] Abbruch angefordert - beende Prozess ...\n")
                    self._kill_script(path)
                elif timeout and time.monotonic() - started > timeout:
                    state["timed_out"] = True
                    emit(f"\n[servermanager] Zeitlimit von {timeout}s überschritten - beende Prozess ...\n")
                    self._kill_script(path)

        try:
            if prefix:
                chan.sendall(prefix.encode())
            chan.shutdown_write()
            self._pump(chan, lambda d: emit(decoder.decode(d)), tick=tick)
            emit(decoder.decode(b"", final=True))
            code = chan.recv_exit_status()
            if state["cancelled"]:
                raise CancelledError("Abgebrochen")
            if state["timed_out"]:
                raise SSHError(f"Zeitlimit von {timeout} s überschritten")
            return code
        finally:
            chan.close()

    def _kill_script(self, path: str) -> None:
        pidfile = shlex.quote(path[:-3] + ".pid")
        cmd = (f"p=$(cat {pidfile} 2>/dev/null); [ -n \"$p\" ] && kill -TERM -- -\"$p\" 2>/dev/null; "
               f"sleep 5; [ -n \"$p\" ] && kill -KILL -- -\"$p\" 2>/dev/null; true")
        try:
            self.exec(cmd, root=True, timeout=30)
        except SSHError as exc:
            log.warning("kill failed: %s", exc)

    # ------------------------------------------------------------------
    # detached execution
    # ------------------------------------------------------------------
    def start_detached(self, body: str, key: str, env: Optional[dict] = None) -> dict:
        """Start a script in the background on the remote host (as root)."""
        if not key.replace("-", "").isalnum():
            raise ValueError("invalid key")
        tmp = self.upload_script(self.build_script(body, env))
        d = DETACHED_DIR
        owner = shlex.quote(self.target.username)
        starter = f"""set -e
mkdir -p {d}; chmod 755 {d}
S={d}/{key}.sh; L={d}/{key}.log; R={d}/{key}.rc; P={d}/{key}.pgid
mv -f {shlex.quote(tmp)} "$S"; chown root:root "$S"; chmod 700 "$S"; rm -f "$R" "$R.tmp" "$P"
: > "$L"; chmod 600 "$L"; chown {owner} "$L" 2>/dev/null || true
nohup setsid bash -c 'echo $$ > "$4"; bash "$1" > "$2" 2>&1 < /dev/null; echo $? > "$3.tmp"; mv -f "$3.tmp" "$3"' \
    _ "$S" "$L" "$R" "$P" >/dev/null 2>&1 &
echo started
"""
        res = self.exec(starter, root=True, timeout=60)
        if not res.ok or "started" not in res.stdout:
            raise SSHError(f"Hintergrundprozess konnte nicht gestartet werden: {(res.stderr or res.stdout).strip()}")
        return {"mode": "detached", "key": key, "offset": 0}

    def poll_detached(self, key: str, offset: int, limit: int = 262144) -> tuple[bytes, Optional[int]]:
        """Return (new log bytes, exit code or None while running).

        The exit code is DETACHED_DIED when the process vanished without writing
        its exit code (e.g. reboot, OOM kill).
        """
        d = DETACHED_DIR
        # a process is considered gone when its session leader no longer exists (checked via
        # /proc, which works without root) and still no exit code was written
        cmd = (f"R={d}/{key}.rc; cat $R 2>/dev/null; echo; "
               f"if [ ! -f $R ]; then p=$(cat {d}/{key}.pgid 2>/dev/null); "
               f"if [ -n \"$p\" ] && ! grep -qs '{key}' /proc/$p/cmdline && [ ! -f $R ]; then echo __SM_DEAD__; fi; fi; "
               f"echo __SM_SEP__; tail -c +{offset + 1} {d}/{key}.log 2>/dev/null | head -c {limit}")
        chan = self._open(cmd, combine=False)
        data = bytearray()
        try:
            chan.shutdown_write()
            self._pump(chan, data.extend, timeout=60, what="Job-Log lesen")
        finally:
            chan.close()
        head, sep, body = bytes(data).partition(b"__SM_SEP__\n")
        if not sep:
            raise SSHError("unerwartete Antwort beim Lesen des Job-Logs")
        head_txt = head.decode(errors="replace")
        if "__SM_DEAD__" in head_txt:
            return body, DETACHED_DIED
        rc_txt = head_txt.strip()
        rc = int(rc_txt) if rc_txt.lstrip("-").isdigit() else None
        return body, rc

    def cancel_detached(self, key: str) -> None:
        d = DETACHED_DIR
        cmd = (f"p=$(cat {d}/{key}.pgid 2>/dev/null); [ -n \"$p\" ] && kill -TERM -- -\"$p\" 2>/dev/null; "
               f"sleep 5; [ -n \"$p\" ] && kill -KILL -- -\"$p\" 2>/dev/null; "
               f"[ -f {d}/{key}.rc ] || echo 143 > {d}/{key}.rc; true")
        self.exec(cmd, root=True, timeout=30)

    def cleanup_detached(self, key: str) -> None:
        d = DETACHED_DIR
        try:
            self.exec(f"rm -f {d}/{key}.log {d}/{key}.rc {d}/{key}.pid {d}/{key}.pgid {d}/{key}.sh",
                      root=True, timeout=30)
        except SSHError:
            pass

    # ------------------------------------------------------------------
    # files
    # ------------------------------------------------------------------
    def download_root(self, remote_path: str, fh, on_progress: Optional[Callable[[int], None]] = None,
                      cancel: Optional[CancelCB] = None) -> int:
        """Stream a (root readable) remote file into ``fh``."""
        return self.stream_cmd(f"cat {shlex.quote(remote_path)}", fh, root=True, on_progress=on_progress,
                               cancel=cancel)

    def stream_cmd(self, cmd: str, fh, root: bool = True, on_progress: Optional[Callable[[int], None]] = None,
                   cancel: Optional[CancelCB] = None) -> int:
        """Stream the stdout of ``cmd`` into the binary file object ``fh``."""
        prefix = None
        if root:
            cmd, prefix = self._root_wrap(cmd)
        chan = self._open(cmd, combine=False)
        state = {"total": 0, "last": 0}
        err = bytearray()

        def write(chunk: bytes) -> None:
            fh.write(chunk)
            state["total"] += len(chunk)
            if on_progress and state["total"] - state["last"] > (8 << 20):
                state["last"] = state["total"]
                on_progress(state["total"])

        def tick() -> None:
            if cancel and cancel():
                raise CancelledError("Abgebrochen")

        def on_err(chunk: bytes) -> None:
            if len(err) < 8192:
                err.extend(chunk)

        try:
            if prefix:
                chan.sendall(prefix.encode())
            chan.shutdown_write()
            self._pump(chan, write, on_err, tick=tick)
            code = chan.recv_exit_status()
            if code != 0:
                raise SSHError(f"Übertragung fehlgeschlagen ({code}) {err.decode(errors='replace').strip()[:500]}")
            return state["total"]
        finally:
            chan.close()

    def upload_root(self, fh, remote_path: str, mode: str = "600") -> int:
        """Stream ``fh`` to a root owned remote file (via sudo if needed)."""
        tmp = f"/tmp/.sm-up-{uuid.uuid4().hex}"
        chan = self._open(f"umask 077 && cat > {tmp}", combine=False)
        total = 0
        try:
            while True:
                chunk = fh.read(1 << 20)
                if not chunk:
                    break
                chan.sendall(chunk)
                total += len(chunk)
            chan.shutdown_write()
            code = chan.recv_exit_status()
        finally:
            chan.close()
        if code != 0:
            raise SSHError("Upload fehlgeschlagen")
        dest = shlex.quote(remote_path)
        self.check(f"install -m {mode} -o root -g root {tmp} {dest} && rm -f {tmp}", root=True)
        return total


def test_connection(target: Target, on_new_host_key=None) -> str:
    with Connection(target, on_new_host_key) as conn:
        return conn.check("hostname -f 2>/dev/null || hostname", timeout=30).strip()
